# Generated by Django 3.1 on 2020-08-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='quantity_reserved',
            field=models.IntegerField(default=0),
        ),
    ]
