# Generated by Django 3.1 on 2020-09-04 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_book_quantity_reserved'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservedBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=60)),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='quantity_reserved',
        ),
    ]
