# Generated by Django 3.1 on 2020-09-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200904_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservedbook',
            name='book_id',
            field=models.IntegerField(default=0),
        ),
    ]
